config/routes.rb
Openfoodnetwork::Application.routes.draw do
  root :to => 'home#index'

  get "/#/login", to: "home#index", as: :spree_login

  get "/map", to: "map#index", as: :map

  get "/register", to: "registration#index", as: :registration
  get "/register/auth", to: "registration#authenticate", as: :registration_auth

  resource :shop, controller: "shop" do
    get :products
    post :order_cycle
    get :order_cycle
  end

  resources :groups
  resources :producers

  get '/checkout', :to => 'checkout#edit' , :as => :checkout
  put '/checkout', :to => 'checkout#update' , :as => :update_checkout
  get '/checkout/paypal_payment/:order_id', to: 'checkout#paypal_payment', as: :paypal_payment

  resources :enterprises do
    collection do
      get :suppliers
      get :distributors
      post :search
      get :check_permalink
    end

    member do
      get :shop_front # new world
      get :shop # old world
    end
  end
  get '/:id/shop', to: 'enterprises#shop', as: 'enterprise_shop'

  devise_for :enterprise, controllers: { confirmations: 'enterprise_confirmations' }

  namespace :admin do
    resources :order_cycles do
      post :bulk_update, on: :collection, as: :bulk_update
      get :clone, on: :member
    end

    resources :enterprises do
      collection do
        get :for_order_cycle
        post :bulk_update, as: :bulk_update
      end

      member do
        put :set_sells
      end

      resources :producer_properties do
        post :update_positions, on: :collection
      end
    end

    resources :enterprise_relationships
    resources :enterprise_roles

    resources :enterprise_fees do
      post :bulk_update, :on => :collection, :as => :bulk_update
    end

    resources :enterprise_groups do
      get :move_up
      get :move_down
    end

    resources :variant_overrides do
      post :bulk_update, on: :collection
    end
  end

  namespace :api do
    resources :enterprises do
      post :update_image, on: :member
      get :managed, on: :collection
      get :accessible, on: :collection
    end
    resources :order_cycles do
      get :managed, on: :collection
      get :accessible, on: :collection
    end
  end

  get "about_us", :controller => 'home', :action => "about_us"

  namespace :open_food_network do
    resources :cart do
      post :add_variant
    end
  end

  # Mount Spree's routes
  mount Spree::Core::Engine, :at => '/'

end


# Overriding Devise routes to use our own controller
Spree::Core::Engine.routes.draw do
  devise_for :spree_user,
             :class_name => 'Spree::User',
             :controllers => { :sessions => 'spree/user_sessions',
                               :registrations => 'user_registrations',
                               :passwords => 'user_passwords' },
             :skip => [:unlocks, :omniauth_callbacks],
             :path_names => { :sign_out => 'logout' },
             :path_prefix => :user
end



Spree::Core::Engine.routes.prepend do
  match '/admin/reports/orders_and_distributors' => 'admin/reports#orders_and_distributors', :as => "orders_and_distributors_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/order_cycle_management' => 'admin/reports#order_cycle_management', :as => "order_cycle_management_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/group_buys' => 'admin/reports#group_buys', :as => "group_buys_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/bulk_coop' => 'admin/reports#bulk_coop', :as => "bulk_coop_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/payments' => 'admin/reports#payments', :as => "payments_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/orders_and_fulfillment' => 'admin/reports#orders_and_fulfillment', :as => "orders_and_fulfillment_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/users_and_enterprises' => 'admin/reports#users_and_enterprises', :as => "users_and_enterprises_admin_reports",  :via  => [:get, :post]
  match '/admin/products/bulk_edit' => 'admin/products#bulk_edit', :as => "bulk_edit_admin_products"
  match '/admin/orders/bulk_management' => 'admin/orders#bulk_management', :as => "admin_bulk_order_management"
  match '/admin/reports/products_and_inventory' => 'admin/reports#products_and_inventory', :as => "products_and_inventory_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/customers' => 'admin/reports#customers', :as => "customers_admin_reports",  :via  => [:get, :post]
  match '/admin', :to => 'admin/overview#index', :as => :admin
  match '/admin/payment_methods/show_provider_preferences' => 'admin/payment_methods#show_provider_preferences', :via => :get


  namespace :api, :defaults => { :format => 'json' } do
    resources :users do
      get :authorise_api, on: :collection
    end

    resources :products do
      collection do
        get :managed
        get :bulk_products
        get :distributable
        get :overridable
      end
      delete :soft_delete

      resources :variants do
        delete :soft_delete
      end
    end

    resources :orders do
      get :managed, on: :collection
    end
  end

  namespace :admin do
    get '/search/known_users' => "search#known_users", :as => :search_known_users

    resources :products do
      get :product_distributions, on: :member

      post :bulk_update, :on => :collection, :as => :bulk_update
    end
  end

  resources :orders do
    get :clear, :on => :collection
    get :order_cycle_expired, :on => :collection
  end

end

app/views/spree/admin/distributors/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <%= button_link_to "New Distributor", spree.new_admin_distributor_path, :icon => 'add', :id => 'admin_new_distributor_link' %>
    </li>
  </ul>
  <br class="clear" />
</div>

<%= form_for @distributor_set, :url => bulk_update_admin_distributors_path do |f| %>
  <table class="index" id="listing_distributors">
    <thead>
      <tr data-hook="distributors_header">
        <th>Name</th>
        <th>Next Collection Date/Time</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :distributors do |distributor_form| %>
        <% distributor = distributor_form.object %>
        <tr>
          <td><%= link_to distributor.name, spree.admin_distributor_path(distributor) %></td>
          <td><%= distributor_form.text_field :next_collection_at %></td>
          <td><%= distributor.description %></td>
          <td data-hook="admin_users_index_row_actions">
            <%= link_to_edit distributor, :class => 'edit' %> &nbsp;
            <%= link_to_delete distributor %>
          </td>
        </tr>
      <% end %>
      <% if @distributors.empty? %>
        <tr><td colspan="4"><%= t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>

  <%= f.submit 'Update' %>
<% end %>

app/views/spree/admin/distributors/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @distributor } %>

<%= form_for [:admin, @distributor] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/distributors/show.html.haml
%h1 Distributor
%table
  %tr
    %th Name:
    %td= @distributor.name
  %tr
    %th Description:
    %td= @distributor.description
  %tr
    %th Extended Description:
    %td= @distributor.long_description.andand.html_safe
  %tr
    %th Contact person:
    %td= @distributor.contact
  %tr
    %th Phone number:
    %td= @distributor.phone
  %tr
    %th Email:
    %td= @distributor.email
  %tr
    %th Pickup address:
    %td= render 'spree/shared/address', :address => @distributor.pickup_address
  %tr
    %th Next collection date/time:
    %td= @distributor.next_collection_at
  %tr
    %th Regular pickup times:
    %td= @distributor.pickup_times
  %tr
    %th ABN:
    %td= @distributor.abn
  %tr
    %th ACN:
    %td= @distributor.acn
  %tr
    %th URL:
    %td= @distributor.url
%p
  = link_to :Edit, spree.edit_admin_distributor_path(@distributor), :class => 'edit_distributor'
  = t(:or)
  = link_to t(:back), spree.admin_distributors_path